
fluentd:
  ports: ["24224:24224"]
  image: gregorycox/fluentd-container
  privileged: true
  volumes:
    - /var/lib/docker/containers:/var/lib/docker/containers
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - LOG_GROUP_NAME=${LOG_GROUP_NAME}
    - AWS_REGION=${AWS_REGION}
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.pull_image: always

