zookeeper-1:
  environment:
    ZOO_MY_ID: '1'
    ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888 server.4=zookeeper-4:2888:3888 server.5=zookeeper-5:2888:3888
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/zookeeper-2,io.rancher.stack_service.name=$${stack_name}/zookeeper-3,io.rancher.stack_service.name=$${stack_name}/zookeeper-4,io.rancher.stack_service.name=$${stack_name}/zookeeper-5
  tty: true
  image: zookeeper:3.4.9
  stdin_open: true
zookeeper-2:
  environment:
    ZOO_MY_ID: '2'
    ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888 server.4=zookeeper-4:2888:3888 server.5=zookeeper-5:2888:3888
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/zookeeper-1,io.rancher.stack_service.name=$${stack_name}/zookeeper-3,io.rancher.stack_service.name=$${stack_name}/zookeeper-4,io.rancher.stack_service.name=$${stack_name}/zookeeper-5
  tty: true
  image: zookeeper:3.4.9
  stdin_open: true
zookeeper-3:
  environment:
    ZOO_MY_ID: '3'
    ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888 server.4=zookeeper-4:2888:3888 server.5=zookeeper-5:2888:3888
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/zookeeper-1,io.rancher.stack_service.name=$${stack_name}/zookeeper-2,io.rancher.stack_service.name=$${stack_name}/zookeeper-4,io.rancher.stack_service.name=$${stack_name}/zookeeper-5
  tty: true
  image: zookeeper:3.4.9
  stdin_open: true
zookeeper-4:
  environment:
    ZOO_MY_ID: '4'
    ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888 server.4=zookeeper-4:2888:3888 server.5=zookeeper-5:2888:3888
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/zookeeper-1,io.rancher.stack_service.name=$${stack_name}/zookeeper-2,io.rancher.stack_service.name=$${stack_name}/zookeeper-3,io.rancher.stack_service.name=$${stack_name}/zookeeper-5
  tty: true
  image: zookeeper:3.4.9
  stdin_open: true
zookeeper-5:
  environment:
    ZOO_MY_ID: '5'
    ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888 server.4=zookeeper-4:2888:3888 server.5=zookeeper-5:2888:3888
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/zookeeper-1,io.rancher.stack_service.name=$${stack_name}/zookeeper-2,io.rancher.stack_service.name=$${stack_name}/zookeeper-3,io.rancher.stack_service.name=$${stack_name}/zookeeper-4
  tty: true
  image: zookeeper:3.4.9
  stdin_open: true
