name: Apache Zookeeper
description: |
  Zookeeper cluster
version: 0.0.1
category: Clustering
maintainer: "Kevin McGrath <keivn.mcgrath@sungardas.com>"
minimum_rancher_version: v1.0.0
license: Apache-2.0
