name: Apache Zookeeper
description: |
  Zookeeper cluster - 5 node
version: 3.4.8-rancher1
category: Clustering
maintainer: "Kevin McGrath <keivn.mcgrath@sungardas.com>"
minimum_rancher_version: v1.0.0
license: Apache-2.0
