name: gocd-server
description: |
  (Experimental) Gocd server
version: 0.0.1-rancher1
category: Continuous Integration
maintainer: "Greg Cox <gregory.cox@sungardas.com>"
minimum_rancher_version: v0.59.0
license: 
